import type { PlanState } from '../schema/plan.schema'
import { normalizeState } from './normalize'

/**
 * Compact array-form encoding of a PlanState, ported from
 * retirement-engine.js's compactState/expandState — same shape, so a link
 * generated by the legacy calculator would decode here too (not that the
 * two apps share links, per docs/retirement-react-rewrite-plan.md §5.5,
 * but there's no reason to invent a less compact format). Wrapped by the
 * useShareLink hook (persistence/shareLink.ts) for compression + URL
 * plumbing.
 */
export type CompactPlan = {
  v: 2
  y: [number, number, number]
  ac: [number, number, number, number, number]
  c: [number, number, number, number, number]
  /** 6th element (frequency) is optional so a pre-frequency share link (5 elements) still decodes — defaults to 'annual'. */
  i: [string, string, number, number, number, ('annual' | 'monthly')?][]
  sp: [number]
  spm: ['flat' | 'items']
  si: [string, string, number, string, string, number | string, number | string][]
  ph: [number, number, number, number, number, number]
  hc: [number, number, number, number, number]
  lt: [number, number, number, number]
  oo: [string, number, number][]
  a: [number, number, number, number, number, number, number, number]
  st: [string, number, number, string]
  /** Optional so a pre-legacy-goal share link still decodes — the goal defaults to disabled. */
  lg?: [number, number, number]
}

export function compactState(state: PlanState): CompactPlan {
  const S = normalizeState(state)
  const { you: y, accounts: ac, contributions: c, spending: sp, assumptions: a, strategy: st } = S
  const { phased: ph, healthcare: hc, ltc } = sp
  return {
    v: 2,
    y: [y.currentAge, y.retireAge, y.endAge],
    ac: [ac.taxable, ac.traditional, ac.roth, ac.cash, ac.hsa],
    c: [c.taxable, c.traditional, c.roth, c.hsa, c.employerMatch],
    i: S.income.map((x) => [x.type, x.label, x.amount, x.startAge, x.cola ? 1 : 0, x.frequency]),
    sp: [sp.baseline],
    spm: [sp.mode],
    si: sp.items.map((it) => [it.label, it.category, it.amount, it.frequency, it.inflation, it.startAge ?? '', it.endAge ?? '']),
    ph: [ph.enabled ? 1 : 0, ph.goGo, ph.slowGo, ph.noGo, ph.slowGoAge, ph.noGoAge],
    hc: [hc.enabled ? 1 : 0, hc.preMedicarePremium, hc.medicareAnnual, hc.irmaaTier, hc.medicalInflation],
    lt: [ltc.enabled ? 1 : 0, ltc.annualCost, ltc.years, ltc.startAge],
    oo: sp.oneOffs.map((o) => [o.label, o.amount, o.age]),
    a: [a.returnAccum, a.returnRetire, a.inflation, a.medicalInflation, a.volatility, a.taxRate, a.taxableGainFraction, a.contributionGrowth],
    st: [st.withdrawalMethod, st.ssClaimAge, st.monteCarloIterations, st.withdrawalOrder.join('|')],
    lg: [S.legacy.enabled ? 1 : 0, S.legacy.amountPerHeir, S.legacy.heirs],
  }
}

export function expandState(d: unknown): PlanState {
  const src = d as Partial<CompactPlan> | null | undefined
  if (!src || src.v !== 2 || !Array.isArray(src.y)) return normalizeState(d) // unknown form; best-effort
  const out: Record<string, unknown> = {}
  out.you = { currentAge: src.y[0], retireAge: src.y[1], endAge: src.y[2] }
  if (Array.isArray(src.ac)) out.accounts = { taxable: src.ac[0], traditional: src.ac[1], roth: src.ac[2], cash: src.ac[3], hsa: src.ac[4] }
  if (Array.isArray(src.c)) out.contributions = { taxable: src.c[0], traditional: src.c[1], roth: src.c[2], hsa: src.c[3], employerMatch: src.c[4] }
  if (Array.isArray(src.i)) out.income = src.i.map((x) => ({ type: x[0], label: x[1], amount: x[2], startAge: x[3], cola: !!x[4], frequency: x[5] ?? 'annual' }))

  const spending: Record<string, unknown> = {}
  if (Array.isArray(src.sp)) spending.baseline = src.sp[0]
  if (Array.isArray(src.spm)) spending.mode = src.spm[0] === 'items' ? 'items' : 'flat'
  if (Array.isArray(src.si)) {
    spending.items = src.si.map((x) => ({
      label: x[0],
      category: x[1],
      amount: x[2],
      frequency: x[3],
      inflation: x[4],
      startAge: x[5] === '' || x[5] == null ? null : Number(x[5]),
      endAge: x[6] === '' || x[6] == null ? null : Number(x[6]),
    }))
  }
  if (Array.isArray(src.ph)) spending.phased = { enabled: !!src.ph[0], goGo: src.ph[1], slowGo: src.ph[2], noGo: src.ph[3], slowGoAge: src.ph[4], noGoAge: src.ph[5] }
  if (Array.isArray(src.hc)) spending.healthcare = { enabled: !!src.hc[0], preMedicarePremium: src.hc[1], medicareAnnual: src.hc[2], irmaaTier: src.hc[3], medicalInflation: src.hc[4] }
  if (Array.isArray(src.lt)) spending.ltc = { enabled: !!src.lt[0], annualCost: src.lt[1], years: src.lt[2], startAge: src.lt[3] }
  if (Array.isArray(src.oo)) spending.oneOffs = src.oo.map((o) => ({ label: o[0], amount: o[1], age: o[2] }))
  out.spending = spending

  if (Array.isArray(src.a)) {
    out.assumptions = {
      returnAccum: src.a[0], returnRetire: src.a[1], inflation: src.a[2], medicalInflation: src.a[3],
      volatility: src.a[4], taxRate: src.a[5], taxableGainFraction: src.a[6], contributionGrowth: src.a[7],
    }
  }
  if (Array.isArray(src.st)) {
    out.strategy = {
      withdrawalMethod: src.st[0], ssClaimAge: src.st[1], monteCarloIterations: src.st[2],
      withdrawalOrder: String(src.st[3] || '').split('|').filter(Boolean),
    }
  }
  if (Array.isArray(src.lg)) out.legacy = { enabled: !!src.lg[0], amountPerHeir: src.lg[1], heirs: src.lg[2] }
  return normalizeState(out)
}
